-- root 用户登录创建新的数据库 
-- mysql -u root -p  123456 
-- 创建 go_react 数据库
--CREATE  DATABASE go_react;  
-- 创建新用户，赋予增删改查 数据库go_react的权限
--GRANT ALL  ON  go_react.* TO 'go_react'@'%' IDENTIFIED BY '123456';
-- 刷新权限
--flush privileges;  
-- 使用 go_react用户登录 mysql
-- mysql -u go_react -p 123456
